# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mimic
name: Credit Karma
description: Mimic multi-protocol service impersonator home page
url: https://creditkarma.github.io/Mimic
baseurl: /Mimic
repository: creditkarma/Mimic
logo: /assets/images/icon.png
search: true
author:
  name: Volodymyr Ladnik
  avatar: /assets/images/bio-photo.jpg
  bio: "My awesome biography constrained to a sentence or two goes here."
  location: San Francisco, USA

include:
  - _pages
  - "*.html"

plugins:
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - packages
  - vendor/bundle/
  - dist
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
